### ISSUE TITLE
Surfaceless API changes are challenging

### ISSUE THREAD

**Issue by jdm** [pcwalton/surfman#34]
Given the difficulties I've had trying to integrate the changes from https://github.com/pcwalton/surfman/commit/08b9448c139b9feddf7d2a32f1a0899c3ff73d66 and https://github.com/pcwalton/surfman/commit/1b58d22aeea174e10fd941937be8b68e43920dbc into Servo (ie. https://github.com/servo/servo/pull/24629), I'm concerned that it's going to impede our ability to get the D3D non-readback changes merged quickly, since https://github.com/pcwalton/surfman/pull/32 needs to be applied. I propose the following:
* revert the surfaceless branch merge on master so we're back at https://github.com/pcwalton/surfman/commit/7985b2f12ea48fe0b83de3880fdce84cf016030d
* merge #32 
* create a pull request for the surfaceless branch, and don't merge it until the work to successfully update Servo and surfman-chains to the new API is complete

This will avoid blocking any further Servo updates of surfman on work that has not been integrated.

**Comment by Manishearth** [comment]
This plan sounds good to me, we should try for a readback master build asap

**Comment by jdm** [comment]
This was addressed.
