### ISSUE TITLE
Binding a surface to the current OSMesa context doesn't update the surface data

### ISSUE THREAD

**Issue by asajeffrey** [pcwalton/surfman#35]
The definition at  https://github.com/pcwalton/surfman/blob/8f97a7bb8ab7a6c5e5b4ab23c0d42805847c9daa/surfman/src/platform/generic/osmesa/context.rs#L271 doesn't call `OSMesaMakeCurrent` to update the pixel data, so subsequent operations are done on the old pixel data, not the new surface pixels.

**Comment by Manishearth** [comment]
When this gets fixed we should also undo [this fix](https://github.com/servo/servo/pull/24676#issuecomment-552599706)

**Comment by jdm** [comment]
Possibly this ends up being the same resolution as #36?

**Comment by pcwalton** [comment]
Fixed in 0.2 by not using OSMesa anymore
