### ISSUE TITLE
Add a way to create surfaces from texture arrays

### ISSUE THREAD

**Issue by Manishearth** [pcwalton/surfman#42]
https://github.com/pcwalton/surfman/blob/6705a9aaa8f33ac1324fdb1913242800e68c7720/surfman/src/platform/windows/angle/surface.rs#L219-L224

We currently have a way to create surfaces from a texture, but the ideal way to render on the Hololens is to submit a single texture array with two textures in it. For this we need to be able to create surfaces for texture array elements, or otherwise support blitting two regions of one texture onto two separate textures in an array.

**Comment by Manishearth** [comment]
>  Is it possible to do one instanced blit from RGBA double wide to BGRA texture array?

> Yes. An instanced drawcall can be used to draw to a texture array with color and layout conversion.

^ if we could set up a way to do that, that would be ideal

cc @pcwalton @jdm I don't understand enough ANGLE or d3d11 to know what the best approach is here

**Comment by pcwalton** [comment]
I think the approach we discussed on IRC will work. I'll leave this open for now.

**Comment by pcwalton** [comment]
Closing for now; feel free to reopen.
